apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: architecture-docs
  description: System Architecture Documentation
  tags: [docs, architecture]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: platform-team
