apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: The Platform Engineering Team
  title: Platform Team
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform@example.com
    picture: https://avatars.dicebear.com/api/identicon/platform-team.svg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
spec:
  profile:
    displayName: Alice Engineer
    email: alice@example.com
    picture: https://avatars.dicebear.com/api/avataaars/alice.svg
  memberOf: [platform-team]
