apiVersion: core.openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
spec:
  displayName: Development
  description: Development environment for testing
  dnsPrefix: dev
  isCritical: false
