apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-experience
  description: The Developer Experience Team
  title: Developer Experience Team
spec:
  type: team
  profile:
    displayName: Developer Experience Team
    email: dev-experience@example.com
    picture: https://avatars.dicebear.com/api/identicon/dev-experience.svg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: arakaki
spec:
  profile:
    displayName: Marcelo Arakaki
    email: arakaki@example.com
    picture: https://avatars.dicebear.com/api/avataaars/arakaki.svg
  memberOf: [dev-experience]
